# Generated by Django 4.0.2 on 2022-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantGeneralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('fathername', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=200)),
                ('alternameemail', models.CharField(max_length=200)),
                ('whatsappnumber', models.CharField(max_length=50)),
            ],
        ),
    ]
