# Generated by Django 4.0.3 on 2022-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=300)),
                ('eventdesc', models.TextField(max_length=1000)),
                ('eventmode', models.CharField(max_length=200)),
                ('eventhost', models.CharField(max_length=300)),
                ('eventvenue', models.TextField(max_length=1000)),
                ('eventnoattendees', models.CharField(max_length=200)),
                ('eventcontactname', models.CharField(max_length=100)),
                ('eventcontactemail', models.CharField(max_length=200)),
                ('eventcontactphoneno', models.CharField(max_length=200)),
                ('eventposter', models.ImageField(blank=True, null=True, upload_to='')),
                ('eventadposter', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
