# Generated by Django 4.0.3 on 2022-03-12 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='eventfromdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='eventtodate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
