# Generated by Django 4.0.3 on 2022-03-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicteapp', '0002_eventregistration_eventfromdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
