# Generated by Django 4.0.2 on 2022-03-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicteapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
