# Generated by Django 4.0.2 on 2022-03-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicteapp', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('fathername', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=200)),
                ('alternameemail', models.CharField(max_length=200)),
                ('whatsappnumber', models.CharField(max_length=50)),
                ('institutename', models.CharField(max_length=150)),
                ('instituteweblink', models.CharField(max_length=150)),
                ('instituteaddress', models.CharField(max_length=700)),
                ('institutecity', models.CharField(max_length=150)),
                ('institutedstate', models.CharField(max_length=150)),
                ('institutedistrict', models.CharField(max_length=150)),
                ('instituteemail', models.CharField(max_length=150)),
                ('institutetype', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
            ],
        ),
    ]
