# Generated by Django 4.0.2 on 2022-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicteapp', '0007_generaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriumData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiname', models.CharField(max_length=500)),
                ('audiaddress', models.CharField(max_length=400)),
                ('audicapacity', models.CharField(max_length=50)),
            ],
        ),
    ]
